export const LOAD_IMAGES_SUCCESS = 'LOAD_IMAGES_SUCCESS';
export const ADD_IMAGE_TO_FAVORITE = 'ADD_IMAGE_TO_FAVORITE';
export const REMOVE_IMAGE_FROM_FAVORITES = 'REMOVE_IMAGE_FROM_FAVORITES';
export const LOAD_FAVORITES_FROM_STORAGE = 'LOAD_FAVORITES_FROM_STORAGE';

